### ISSUE TITLE
你好，请问我使用--loss=1*GAN作为损失函数时提示 ModuleNotFoundError: No module named 'utility'

### ISSUE THREAD

**Issue by zhang13359** [Shaosifan/HSENet#12]
```
(r_esrgan) PS D:\HSENet> pip install utility
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
......
Installing collected packages: utility
Successfully installed utility-1.0
```
我使用pip install utility 安装后，依然报错
当我直接在命令行打开python 直接导入utility，仍然提示找不到模块
```
(r_esrgan) PS D:\HSENet> python
Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import utility
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'utility'

```

**Comment by Shaosifan** [comment]
> ```
> (r_esrgan) PS D:\HSENet> pip install utility
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> ......
> Installing collected packages: utility
> Successfully installed utility-1.0
> ```
> 
> 我使用pip install utility 安装后，依然报错 当我直接在命令行打开python 直接导入utility，仍然提示找不到模块
> 
> ```
> (r_esrgan) PS D:\HSENet> python
> Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import utility
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'utility'
> ```

你可以使用codes/[utils.py](https://github.com/Shaosifan/HSENet/blob/main/codes/utils.py)里面的make_optimizer和make_scheduler函数替代这里utility
