### ISSUE TITLE
请问数据路径的相关问题

### ISSUE THREAD

**Issue by Yu-Wang-0801** [Shaosifan/HSENet#4]
![image](https://user-images.githubusercontent.com/49390007/188454578-ef8eec44-9535-4aa0-b399-06ace74c628a.png)您好，这是我尝试训练您的代码出现的问题，特请问应该如何修改数据路径，谢谢您！
![image](https://user-images.githubusercontent.com/49390007/188455097-00559558-7541-4bed-a7da-ef18ebd045f1.png)
这是数据摆放的路径，请问如何修改？

**Comment by Shaosifan** [comment]
您好，我已经将数据更新了一下，其中HR_x2x4更新为HR_x2和HR_x4
