### ISSUE TITLE
can not train the model as instructed in readme file

### ISSUE THREAD

**Issue by jhrcws** [Shaosifan/HSENet#5]
as your side in the "train" part:# x4
python demo_train.py --model=HSENET --dataset=UCMerced --scale=4 --patch_size=192 --ext=img --save=HSENETx4_UCMerced
# x3
python demo_train.py --model=HSENET --dataset=UCMerced --scale=3 --patch_size=144 --ext=img --save=HSENETx3_UCMerced
# x2
python demo_train.py --model=HSENET --dataset=UCMerced --scale=2 --patch_size=96 --ext=img --save=HSENETx2_UCMerced

 I can not find the model, dataset and scale setting parameters in demo_train.py file
![1673098212814](https://user-images.githubusercontent.com/122160936/211153412-539ad3a3-3197-4b38-ad6f-b941f5e8ee51.png)
![1673098250631](https://user-images.githubusercontent.com/122160936/211153421-5dd910f7-0a80-45a8-8a26-b7a88ea70261.png)

**Comment by Shaosifan** [comment]
Hi, the setting parameters of model, dataset, and scale can be found in option.py.

**Comment by jhrcws** [comment]
thanks for your reply. At the same time, I see many modules and .py files in the HESNet-main files, and as a newbie in deep leaning field, I am very confused what to do to reproduce the results in your paper.  So would  you tell me what should I do in the first sencond third... steps to reproduce the results in the paper?  I will appreciate for your valuable help.

![a23b6971cc6a8c8d61e9de0e23288ab](https://user-images.githubusercontent.com/122160936/212527796-cef1a7d3-cb22-4392-b8d7-35a709f9469c.png)

**Comment by Shaosifan** [comment]
The main steps to use this repository can be found in README.md
1. Install some requirements.
2. Download the dataset and set paths in [data/init.py](https://github.com/Shaosifan/HSENet/blob/main/codes/data/__init__.py)
3. Train HSENet using demo_train.py.
4. Test the trained HSENet using demo_deploy.py.
5. Make evaluations using calculate_PSNR_SSIM.py.
