### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by Zhang-Jinwei** [Shaosifan/HSENet#6]
Hello, thank you very much for your sharing. We ran into some problems when reproducing your code, may I ask you?
We tried to use the pre-training model to test some of our data, but no matter we chose x4 or x2, it would be reported out of memory, and there was no load on our gpu. Besides, we observed that your pre-training model was not large. 
![image](https://user-images.githubusercontent.com/72846034/228715807-42f265ab-f45d-485b-8ae1-98f98644ab16.png)

**Comment by Shaosifan** [comment]
Hi, I wonder what is the size of your test data. If the size of your data is too large, I suggest you super-resolve it block-by-block by adding the parameter "--test_block": 
`python demo_deploy.py --model=HSENET --scale=4 --test_block
`

**Comment by iswangyifan** [comment]
我也遇到同样的问题，该如何解决呢？

**Comment by Shaosifan** [comment]
> 我也遇到同样的问题，该如何解决呢？

请参考我上一个回答，看是否能够解决

**Comment by iswangyifan** [comment]
已经解决了 谢谢哦
