### ISSUE TITLE
预训练进行测试

### ISSUE THREAD

**Issue by scm-later** [Shaosifan/HSENet#7]
我用这个命令python demo_deploy.py --model=HSENET --scale=2 --test_block ，使用预训练模型进行2倍超分，为什么出来的图像上有横竖的条纹呢，4倍的超分就不会出现这种现象
![2×00005](https://user-images.githubusercontent.com/89558994/230399085-70091d80-c2ea-402e-80a2-6b6d2d0a89b0.jpg)
![4×00005](https://user-images.githubusercontent.com/89558994/230399115-ca9ac8a2-6ce1-4308-b62f-900b81ac3b7a.jpg)

**Comment by Shaosifan** [comment]
我这边暂时没出现这个问题，你这边还存在这个问题么？
