### ISSUE TITLE
关于NWPU-RESISC45数据集

### ISSUE THREAD

**Issue by tarxs** [Shaosifan/HSENet#9]
请问你训练这个数据集是把45个类别的数据放在一起训练一个模型吗，数据太多了，完全训练不了啊

**Comment by Shaosifan** [comment]
您好，请问您是训练哪个模型呢？在论文中，采用NWPU-RESISC45主要是用来训练了一个ResNet-50分类模型，然后来探究不同的SR方法对于分类任务的影响，这些SR方法是采用已经训练好的模型。

**Comment by tarxs** [comment]
> 您好，请问您是训练哪个模型呢？在论文中，采用NWPU-RESISC45主要是用来训练了一个ResNet-50分类模型，然后来探究不同的SR方法对于分类任务的影响，这些SR方法是采用已经训练好的模型。

我想用NWPU的数据集训练你的SR方法以及你的对比SR方法，就像使用ucml数据集一样。因为我尝试了一下，发现非常慢，并且PSNR也达不到用UCML的效果

**Comment by Shaosifan** [comment]
> > 您好，请问您是训练哪个模型呢？在论文中，采用NWPU-RESISC45主要是用来训练了一个ResNet-50分类模型，然后来探究不同的SR方法对于分类任务的影响，这些SR方法是采用已经训练好的模型。
> 
> 我想用NWPU的数据集训练你的SR方法以及你的对比SR方法，就像使用ucml数据集一样。因为我尝试了一下，发现非常慢，并且PSNR也达不到用UCML的效果

相比于UCMerced数据集，NWPU-RESISC45的数据集类别更多，且总共数据图像数目远大于UCMerced数据集（>10倍），训练相同的轮数的话肯定慢不少。因为我没有在NWPU上训练过SR模型，从直觉上看，由于NWPU类别更多，总体的重建难度会更大些。
